README.md
Make a first stab at writing better documentation
- Rewrite instructions to refer to .env.development
- Add a placeholder quickstart for local dev env
=> docs(readme): reference .env.dev

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/docker-compose.yml, docker-compose.yml, package-lock.json, package.json
We want to make the developer experience as smooth as possible. 
Doing everything from within the browser or at least an environment we can control on the user's behalf is an added bonus
- Add config for a CodeSpace devcontainer specific to Starter Kit
- Take the trouble to run a post-create command to `npm i`, prep an env file and run `prisma migrate deploy`
- Tidy up file and package names while we are here
Use https://github.com/codespaces/new?hide_repo_select=true&ref=chore%2Fcodespaces%2Fdevcontainer&repo=610561263
=> chore(codespaces): tailor devcontainer config

prisma/migrations/20230420051446_better_indexes/migration.sql, prisma/schema.prisma
CockroachDB very nice, give insights as to what indexes we can use to improve perf. However, Prisma current does not support [`STORING` clause](https://www.cockroachlabs.com/docs/stable/indexes.html#storing-columns) (i.e. `INCLUDE` clause in postgres), see https://github.com/prisma/prisma/issues/8584, so for now just use the normal indexes.
This PR adds better indices that fits our current app's access patterns. 
Probably can add into our CockroachDB readme docs also in future PRs when we write about why we chose cockroachDB, about its features, etc.
=> feat: add migration for better indexes

.devcontainer/devcontainer.json, README.md, docs/examples/replies.md, package-lock.json, package.json
Take advantage of Recommended Secrets[^1] to allow the user to
conveniently input the API key for Postman within the dev container.
Fixes TOOL-30
[^1]: https://github.blog/changelog/2023-04-24-one-click-into-github-codespaces/#recommended-secrets
=> feat(codespaces): configure secret input for `POSTMAN_API_KEY`

.devcontainer/devcontainer.json, .env.example, README.md, playwright/smoke.test.ts, render.yaml, src/browserEnv.ts, src/pages/sign-in.tsx, src/templates/layouts/DefaultLayout.tsx
Inconsistent naming
Clean up naming so that people know this as Starter Kit
- Consolidate app name to `browserEnv.NEXT_PUBLIC_APP_NAME`
- Allow the user to set the app name via the relevant env var
=> chore(names): standardize what we call this codebase

src/browserEnv.ts, src/lib/mail.ts, src/server/env.ts
People may want to use Starter Kit even if they don't have access to Postman, so allow for this by logging mail to console
=> feat(otp): log to console if Postman not enabled

.env.example
Ensure that .env.example contains a long session secret
Fixes TOOL-45
=> chore(env): specify a long session secret

src/server/trpc.ts
Users who previously had a valid session, then had their row removed from the db, would still be able to access protected routes.
The conditional statement did not attempt to find the user if a session is set in the context.
If no user found:
- destroys session so that frontend gets redirected to the sign-in page
- throw `UNAUTHORIZED` error
**Cons**
- Additional overhead needing to find the user each time a protected route is accessed, but the minor lookup cost is a worthy trade-off for tighter auth.
**Improvements**:
- @karrui mentioned that including a flag to check if a user was soft deleted / their session was invalidated (ironsession is stateless) would be a better way to handle this.
=> fix: deleted user accessing protected routes

.github/workflows/main.yml, package.json
e2e tests failed previously. now they do not.
=> fix: add setup:test script for cicd to avoid migration

.eslintrc.json, src/components/ErrorBoundary/ErrorBoundary.tsx, src/components/ErrorBoundary/ErrorBoundary.types.ts, src/components/ErrorBoundary/ErrorBoundary.utils.ts, src/components/ErrorBoundary/UnexpectedErrorCard.tsx, src/components/Suspense/Suspense.tsx, src/constants/params.ts, src/features/feedback/api/useFilterFeedback.ts, src/features/feedback/components/FeedbackHeader.tsx, src/features/feedback/components/TeamFeedbackFilterBar.tsx, src/features/feedback/components/TeamFeedbackList.tsx, src/features/profile/api/useUser.ts, src/features/sign-in/components/SignInContext.tsx, src/features/sign-in/components/SignInForm.tsx, src/features/sign-in/components/VerificationInput.tsx, src/pages/_app.tsx, src/pages/dashboard.tsx, src/pages/feedback/[id].tsx, src/pages/index.tsx, src/pages/sign-in.tsx, src/utils/error.ts, src/utils/trpc.ts
Our current method of fetching data for pages with query params utilize `getServerSideProps`. We noticed a trend of slow initial load times for these pages as long as ~7s. This is likely (but not confirmed) attributed to Chakra's huge bundle size which slows down the time needed to build the server rendered page.
We had two options
- Attempt to fix `getServerSideProps`'s bundle issues with Chakra - possibly looking into how we can treeshake chakra for server rendered pages to reduce build times
- Introduce CSR patterns in our application
We went with option 2 as that was already in the existing roadmap.
Existing CSR patterns with page based routing was cumbersome as we could not use React 18's `Suspense` and the default `ErrorBoundary` from `react-error-boundary`. 
This led to 2 dx …
=> feat: add error boundaries and suspense usage with TRPC

src/components/ErrorBoundary/ErrorBoundary.tsx
sign in needs a forward slash so the route replaces the entire route instead of being appended to the current path
**Example**
If you try to navigate to `/post/[id]` while unauthenticated, you will be rerouted to `/post/sign-in`
- Append forward slash to start of route
=> fix: add starting slash to sign in redirect

.eslintrc.cjs, package.json
We have two sets of Prettier configs:  
1. `package.json` - Prettier (and its VSCode extension) reads this
2. `.eslintrc.cjs` - ESLint reads this, but [will default to `package.json` if not explicitly configured](https://github.com/prettier/eslint-plugin-prettier#recommended-configuration)
This causes code formatted by the extension to conflict with the linter. 
- Remove the one in `.eslintrc.cjs`, all tools should rely on the config in `package.json` for consistency
- Found some unnecessary rules that are identical to Prettier's defaults, removed them
=> fix: remove duplicate prettier config

src/env.mjs, src/lib/sgid.ts, src/server/modules/auth/sgid/sgid.router.ts, src/server/modules/auth/sgid/sgid.utils.ts
Currently, the sgid client initialisation will be invoked even if the environment variables are not set, resulting in an error. This commit correctly initiates the sgid client only if the enable flag is true
=> fix: make sgid truly optional

src/components/ErrorBoundary/ErrorBoundary.tsx, src/pages/api/trpc/[trpc].ts, src/server/trpc.ts
- fixes error boundary not having a default unexpected error card which gets returned
- switched sequence of conditional statements, previously we could render `fallback` child even if unauthorized error was thrown, but a better flow would be to always just redirect to `/sign-in` page if `UNAUTHORIZED` was thrown
- whenever an `UNAUTHORIZED` error was thrown, destroy session in backend so user will be logged out. 
- there was a scenario where infinite redirects could happen if the session was not destroyed (this can happen when someone throws an `UNAUTHORIZED` error without ctx.session.destroy()
=> fix: error boundary fall back and signout catch all

.github/dependabot.yml
Storybook packages should be updated together to avoid breaking changes, but dependabot updates them separately.
=> chore(ci): make dependabot ignore storybook packages

package-lock.json, package.json, src/lib/logger.ts, src/server/context.ts, src/server/modules/auth/email/__tests__/email.router.test.ts, src/server/modules/post/__tests__/post.router.test.ts, src/server/trpc.ts, src/utils/getClientIp.ts, tests/integration/helpers/iron-session.ts
Adds extra properties to logger context for better observability
- `id`: for better traces across log invocations
- `clientIp`: to track ip of client - helpful during instances where you need to block ip addresses in case of bots
=> chore: add extra log properties

src/env.mjs, src/lib/mail.ts
This PR fixes the bug where validation will fail if Sendgrid SENDGRID_FROM_ADDRESS is not provided. 
Also updates the logging message when neither Postman nor Sendgrid environment variables are provided, to change from the help text referencing Postmark to Sendgrid
=> fix: allow empty string in SENDGRID_FROM_ADDRESS env var validation

.github/workflows/main.yml, package.json
CI tests will fail when `seed.ts` is not empty.
This occurs because the current `setup:test` step does not perform migrations, resulting in any seed operations to fail.
Currently, the CI stage passes because there are no operations performed in `seed.ts` and so this error does not occur.
Replace the `prisma generate` command in `setup:test` with `prisma migrate deploy`.
We opt to use `prisma migrate deploy` in favour of `prisma migrate dev` as the latter will attempt to create a migration for any pending changes in the schema.
The `prisma generate` step is removed as it is performed in the `postinstall` step.
=> ci: fix missing db migration in setup:test

next.config.mjs, src/lib/auth.ts
1. The webpage does not load during development in Safari. 
2. Login does not work on Safari during development.
The `upgrade-insecure-connections` header is set during development. This causes Safari to use `https` when retrieving other assets hosted on localhost.
The session cookie is not set upon successful login.
Safari does not accept cookies that have  `secure: true` flag that have been sent over an unsecure (`http`) connection.
Unset the `upgrade-insecure-connections` header in non-production environments.
Unset the `secure` flag on the session cookie in non-production environments.
=> fix: allow insecure connections during development

package-lock.json, package.json, src/features/sign-in/components/SignInContext.tsx, src/features/sign-in/components/VerificationInput.tsx
Currently users are able to resend OTP infinite times. This PR blocks the frontend from resending OTP for 60 seconds correctly.
Also replaces `rooks` package with `usehooks-ts` package, since the hooks in `usehooks-ts` has better support for SSR
=> fix: reset timer on resend otp, replace rooks with usehooks-ts

src/features/home/components/EmptyPostList.tsx
=> fix: make empty post list component span grid

src/features/sign-in/components/Emailnput.tsx, src/server/modules/auth/email/email.router.ts
Email addresses for user accounts are treated case sensitive.
This means that email@example.com will create a different user account than Email@example.com.
- Treat all email address input as lowercased on sign in (front end & backend)
=> feat: make email address log in validation case insensitive

src/components/FileButton.tsx
This PR improves the type safety of the `FileButton` component by removing the use of TypeScript generics and replacing it the use of discriminated unions.
As a result, TypeScript correctly infers the `onChange` and `append` variables based on the value of `multiple` and `forwardRef` correctly returns the type of the component since no generics are involved
=> refactor: improve file button typing

src/pages/api/openapi.json.ts, src/server/openapi.ts
- Correct OpenAPI spec to state the use of cookies for auth
- Use `json()`, not `send()`, to ensure spec is only sent as JSON
=> fix(openapi): send spec with `.json()`, use cookie auth

src/components/AppNavbar.tsx, src/components/DashSidebar.tsx, src/pages/home.tsx, src/templates/layouts/ProfileLayout.tsx
https://github.com/opengovsg/starter-kit/assets/10572368/23eee07d-cc7b-4ac6-b3a4-d5ee0a2bc112
For smaller phones (viewport < `sm`), DashSidebar takes up precious screen real-estate, leading to cluttered layout
Preserve as much screen real estate as possible by hiding the sidebar behind a 25% transparent menu button for viewports smaller than `sm`
- For < sm viewports, ensure page layouts are at absolute top left
- Pad new post banner to ensure title not obscured
- Use breakpoint responsive values to render either a sidebar, or a hidden sidebar revealed by an icon button
=> feat(sidebar): render as button menu for < sm viewports

src/components/DashSidebar.tsx
When hidden, the user can still interact with the sidebar items if they click at the right spot
Set `display: none` on sidebar items if `showWhenSmallMobile` is false
=> fix(sidebar): ensure no display when hidden

src/utils/trpc.ts
By default, tRPC will retain its own reference to window.fetch on init. Any changes to or replacements of window.fetch would not be picked up by tRPC, which will affect eg, instrumentation by Datadog RUM.
Fix this by supplying our own fetch implementation that delegates to whatever is the current global `fetch()`.
=> feat(trpc): use fetch fn that directs to window.fetch

package-lock.json, package.json, src/lib/logger.ts, src/server/trpc.ts
Closes #184
Use pino for logging, giving us better logging performance and JSON-first log messages, which are better handled in production by log-processing systems like CloudWatch and Datadog.
Help developers to read and handle logs in development environments with pino-pretty.
- `npm install pino pino-pretty && npm remove winston`
- Rework logging infrastructure to adapt to pino
=> feat(logging): replace winston with pino

.storybook/main.ts, .storybook/preview.tsx, src/components/AppProviders/EnvProvider.tsx, src/components/AppProviders/FeatureProvider.tsx, src/components/AppProviders/index.ts, src/env.mjs, src/hooks/useEnv.ts, src/pages/_app.tsx, src/pages/sign-in/index.tsx, src/templates/layouts/DefaultLayout.tsx
Allows injection of environment variables into chromatic builds.
=> build: include environment variables for chromatic

src/server/modules/auth/sgid/sgid.service.ts
This PR fixes a bug where account creation may fail due to not having the user created prior to linking. This happened because the user was created in a transaction but the account was created without using the transaction connection inside the transaction.
=> fix: use transaction in a transaction

src/components/AuthWrappers/EnforceLoginStatePageWrapper.tsx, src/components/AuthWrappers/PublicPageWrapper.tsx, src/features/sign-in/components/EmailLogin/VerificationInput.tsx, src/features/sign-in/components/SgidCallback.tsx, src/features/sign-in/components/SgidProfileList/SgidProfileList.tsx, src/schemas/url.ts, src/server/modules/auth/sgid/sgid.router.ts, src/utils/url.ts
Fixing a possible open redirect via URL parameter in the `callbackUrl` URL parameter that is appended to the URL when a redirect occurs due to the application session expiring (and receiving a 401 from the server)
=> fix: only allow relative paths for callback URL query param

.env.example, src/env.mjs, src/utils/getBaseUrl.ts, src/utils/url.ts
The previous fix in #274 was not enough and there are some possible strings that could still bypass the `isRelativeUrl` check. This PR adds in a new environment variable `NEXT_PUBLIC_APP_URL` (only required-ish on non-vercel deployments)  to correctly ascertain that the URL to check is a relative URL, by comparing origins and ensuring both origins match.
=> fix: additional fix for possible xss injection

src/server/trpc.ts, tests/integration/helpers/iron-session.ts
This PR adds an additional middleware to ensure that the Content-Type of requests with request body are enforced as application/json.
=> fix: add content type header middleware

src/utils/trpc.ts
When a mutation returns an error that is deemed retryable, it retries. This "feature" may result in multiple POST requests on error codes deemed retryable, which may not be the expected behaviour. For avoidance of any possible idempotency issue, retries are turned off on mutations.
=> feat: disable retries on mutations

package-lock.json, package.json, src/schemas/url.ts, src/utils/email.ts
This PR replaces `UrlValidator` with the newer `createUrlSchema` API from starter-kitty, which is more concise and extendable for use with Zod schemas. It also replaces the `.endsWith` check for `.gov.sg` emails with [`createEmailSchema`](https://kit.open.gov.sg/examples/validators.html#email-validation), which is safe to extend for more custom use cases, e.g. multiple domains, subdomain vs. full match only, etc.
=> refactor: url and email validation

src/server/modules/me/me.router.ts
Simplified user data retrieval by using existing context data instead of making a database query.
Removed the database query in the `me.router.ts` file and directly returned the user data from the context (`ctx.user`) that's already available through the `protectedProcedure`.
1. Make a request to the `/me` endpoint while authenticated
2. Verify that the user data is still returned correctly
3. Confirm that the response time has improved due to the eliminated database query
The `protectedProcedure` already includes the necessary user data in its context, making the additional database query redundant. This change improves performance by eliminating an unnecessary database call while maintaining the same functionality.
=> feat: remove redundant db query in me.get

src/server/modules/auth/email/email.router.ts
Added account record creation during email-based authentication
- Added transaction to create both user and account records during email sign-in
- Implemented email provider account creation using normalized email as the provider account ID
- Maintained existing user creation/update logic while adding the associated account record
1. Sign in with email authentication
2. Verify that a new account record is created in the database with:
- Provider set to "email"
- ProviderAccountId set to the normalized email address
- Correct association with the user ID
To maintain consistency in authentication records across different providers and ensure proper tracking of email-based authentication methods in the accounts table. This change aligns the email authentication flow with other authentication …
=> feat: add email provider when logging in with an email

src/components/AuthWrappers/EnforceLoginStatePageWrapper.tsx, src/utils/url.ts
Utility function `appendWithRedirect` has the following code
```typescript
export const appendWithRedirect = (url: string, redirectUrl?: string) => {
if (!redirectUrl || !isRelativeUrl(redirectUrl)) {
return url
}
return `${url}?${CALLBACK_URL_KEY}=${redirectUrl}`
}
```
However, `redirectUrl` should be encoded with `encodeURIComponent`.
In the `Redirect` component, the encoding there is thereby removed. 
Manually tested simple flow
`localhost:3002/home` -> `http://localhost:3002/sign-in?callbackUrl=%2Fhome` -> `http://localhost:3002/home`
=> fix: urlencode redirect url

next.config.mjs, src/env.mjs, src/pages/_app.tsx, src/server/modules/auth/session.ts, src/server/prisma.ts
There are several checks scattered across starter-kit that follow the pattern `env.NODE_ENV === production ? 'safe': 'unsafe'`.
This is unsafe by default because if `NODE_ENV` is not set in the deployment, it will be `undefined`, falling back to an unsafe value.
This has previously led to [wrong CSP headers being set on production instance of ActiveSG](https://github.com/opengovsg/activesg/pull/2189/).
The unsafe pattern has been replaced with either
- `['test', 'development'].includes(env.NODE_ENV)`
- `env.NODE_ENV !== 'test' && env.NODE_ENV !== 'development'`
where appropriate.
No testing was done because the checks are logically equivalent.
=> feat: make node_env checks safe by default

src/env.mjs, src/pages/_app.tsx
FE was crashing due to referencing server env var `NODE_ENV` in `src/pages/_app.tsx`
This issue comes from PR #383 where we replaced `NODE_ENV` references.
1. Failure to differentiate between `env.NODE_ENV` and `process.env.NODE_ENV`:
- `env.NODE_ENV` is evaluated at runtime
- `process.env.NODE_ENV` is baked during build time.
2. Human factors:
- Lack of manual testing in previous PR (#383)
- Merging the PR before the CI pipeline completed its checks
- Corrected all `NODE_ENV` references to the appropriate types (runtime vs build time)
- Tested locally with `npm run dev` and `npm run build && npm run start`, works perfectly.
=> fix: fe crash due to referencing server env var NODE_ENV

package-lock.json, package.json, src/lib/mail.ts
`starter-kit` depends on `wretch` library in `src/lib/mail.ts > sendMail` function, used for sending OTPs by calling the postman API.
This library is not well reviewed and only has 38k downloads. It doesn't make sense to rely on such a library for what is essentially a fetch wrapper in a small but critical part of `starter-kit`
I have replaced `wretch` with native `fetch`.
The error message object is different, but in `starter-kit` the error is ignored anyway.
Tested locally to ensure feature parity
```bash
npm i wretch@2.8.0
```
```typescript
import wretch from 'wretch'
type SendMailParams = {
recipient: string
body: string
subject: string
}
const params = {
recipient: 'recipient@recipient.com',
body: 'bodybody'
}
```
```typescript
const wretch_response = await …
```
=> chore: replace wretch with native fetch

src/server/modules/auth/sgid/sgid.router.ts
After sgid login, the user is prompted to select a profile.
Whichever profile is selected, the email is sent to the server to be used as the primary identifier.
There is a validation step which checks that the email used is in one of the sgid profiles belonging to the user.
However, there is no case normalization performed on the sgid profile emails during this check.
Therefore, there could be a situation where the sgid profile emails are not lowercased, leading to an error when the user selects the profile.
Normalize the `work_email` when checking if the user selected email is equal to it.
Additionally, the check for whether sgid login is enabled has been made consistent.
=> fix: normalise sgid email

src/features/sign-in/components/SgidErrorFallback/SgidErrorFallback.tsx, src/features/sign-in/components/SgidLogin/SgidLoginButton.tsx, src/schemas/url.ts, src/server/modules/auth/sgid/sgid.router.ts
The SGID OIDC login flow, while currently safe, is prone to open redirect vulnerabilities related to the `landingUrl` parameter. This URL is passed into the `state` parameter and is derived from query params. There is insufficient validation in between the steps of the login flow, thus is quite prone to open redirect vulnerabilities.
This has occurred in [kampung-spirit recently](https://github.com/opengovsg/kampung-spirit/pull/388/) and could be partially exploitable in `armoury`.
To mitigate this, we propose the following changes:
1. **Client-side validation**: Implement validation of the `landingUrl` on the client side and fallback to a safe URL.
2. **Server-side validation**: Add server-side validation in both legs of OIDC and always fallback to a safe URL.
3. **Error fallback …
=> chore: improve sgid state validation

src/env.mjs
This pull request includes a change to the environment variable validation logic in the `src/env.mjs` file. The change introduces a new variable to allow building a Docker image without server-side environment validation.
Environment variable validation improvements:
* [`src/env.mjs`](diffhunk://#diff-4ed47d4643b7ec88e80c88221860b4c9eca9be1cb89d980ab40ed6087ae47caaR173-R177): Added a new constant `isBuild` to check for `BUILD_MODE` in the process environment, allowing the Docker image to be built without server-side environment validation.
=> feat: add additional flag to allow skipping of server env validation

next.config.mjs
This pull request includes a small change to the `next.config.mjs` file. The change adds a comment explaining that the Dockerfile replaces the `output` property with `"standalone"` to allow a custom server.
=> feat: add output config to next.config.mjs for dockerfile replacement

.github/workflows/chromatic.yml, .github/workflows/ci.yml
CodeQL generated alerts for not pinning actions to a specific commit hash.
This is a valid concern for certain actions, especially `xom9ikk/dotenv@v2`, as the maintainer can simply point `v2` at a malicious script instead and exfiltrate env vars.
For other actions, namely `datadog/test-visibility-github-action` and `chromaui/action`, we can trust that they have a proper release process, so actually there is no need to pin it.
For more information, see alerts ([1](https://github.com/opengovsg/starter-kit/security/code-scanning/1), [2](https://github.com/opengovsg/starter-kit/security/code-scanning/2), [3](https://github.com/opengovsg/starter-kit/security/code-scanning/3), [4](https://github.com/opengovsg/starter-kit/security/code-scanning/4), …
=> fix: pin github workflow actions to commit hash

.github/workflows/chromatic.yml, .github/workflows/ci.yml
CodeQL generated alerts for lack of explicit permissions in github workflows.
This is yet another level of hardening, but it is not strictly necessary for us to do so.
However, it is indeed good practice and it does not hurt to add it into the workflow.
See alerts ([6](https://github.com/opengovsg/starter-kit/security/code-scanning/6), [7](https://github.com/opengovsg/starter-kit/security/code-scanning/7), [8](https://github.com/opengovsg/starter-kit/security/code-scanning/8), [9](https://github.com/opengovsg/starter-kit/security/code-scanning/9), [10](https://github.com/opengovsg/starter-kit/security/code-scanning/10), [11](https://github.com/opengovsg/starter-kit/security/code-scanning/11))
For both workflows:
- `checks: write` is required to write check outcome in PRs.
- `contents: …
=> fix: limit permissions for github workflows

package-lock.json, package.json
`starter-kitty-validators@1.2.11` contains a patch for a NextJS open redirect via interception routes.
This change breaks routes containing the following pattern `(.)` or `(..)` or `(...)` or `(..)(..)`
`starter-kit` does not use any routes with the aforementioned pattern, so there is no risk of breaking anything.
=> chore: bump starter-kitty-validators to v1.2.11

.storybook/preview.tsx, src/pages/api/trpc/[trpc].ts, src/utils/trpc.ts
Context
https://opengovproducts.slack.com/archives/C055FUACLJU/p1737346863461179
This pull request includes several changes to the TRPC client configuration to improve logging and simplify the codebase. The most important changes involve replacing the `httpBatchLink` with `httpLink` and disabling query batching.
Changes to TRPC client configuration:
* [`.storybook/preview.tsx`](diffhunk://#diff-e201de4e2ea4ee79f492c0495d7f3fce6389034fe26bfb8f3c877f8c03edf914L16-R16): Replaced `httpBatchLink` with `httpLink` in the import statement and in the `SetupDecorator` function. [[1]](diffhunk://#diff-e201de4e2ea4ee79f492c0495d7f3fce6389034fe26bfb8f3c877f8c03edf914L16-R16) [[2]](diffhunk://#diff-e201de4e2ea4ee79f492c0495d7f3fce6389034fe26bfb8f3c877f8c03edf914L74-R74)
* …
=> feat: disable trpc batching

package-lock.json, package.json
This pull request updates the `@aws-sdk/client-s3` and `@aws-sdk/s3-request-presigner` dependency packages.
Dependency updates:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L45-R46): Upgraded `@aws-sdk/client-s3` from version `3.689.0` to `3.774.0`.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L45-R46): Upgraded `@aws-sdk/s3-request-presigner` from version `3.689.0` to `3.774.0`.
=> build(deps): bump @aws-sdk packages to 3.774.0

src/server/trpc.ts
[Good pre-read](https://blog.insiderattack.net/how-not-to-measure-time-in-programming-11089d546180)
Tracking of spans might be inaccurate as a time-of-day clock is subject to moving forward or backward due to NTP stepping and is subject to leap second adjustments. Using a monotonic clock allows us to have a more accurate measurement of elapsed time on a single node. 
Did a similar fix for [ASG](https://github.com/opengovsg/activesg/pull/2664)
=> fix: use monotonic clock for measuring spans
