src/components/DashSidebar.tsx
=> fix: remove link to missing settings page

README.md
- Follow up on #71 by declaring `POSTMAN_API_KEY` optional
- Point to opengovsg/starter-kit-docs
- Add `DATABASE_URL` env var to `npm run setup` line
Fixes TOOL-35
Fixes TOOL-34
=> docs(readme): clean up and polish

package-lock.json, package.json
Reverts opengovsg/starter-kit#82 after @karrui spotted branch failures
=> Revert "build(deps-dev): bump @playwright/test from 1.31.2 to 1.33.0"

package-lock.json, package.json
Reverts opengovsg/starter-kit#91
Revert the revert
=> Revert "Revert "build(deps-dev): bump @playwright/test from 1.31.2 to 1.33.0""

src/server/prisma.ts
Logs even for development is alittle too noisy now. Suggesting to remove query logging even for development.
Closes TOOL-36
=> chore: disable query logging for dev

.env.example, src/env.mjs
This PR fixes a few bugs that may hinder startup of the application in the `.env.example` file.
=> fix: invalid example env file

.env.example, package-lock.json, package.json, src/env.mjs, src/features/sign-in/components/Emailnput.tsx, src/lib/mail.ts
allows users who do not have access to postman to still use sendgrid
docs are also up at https://github.com/opengovsg/starter-kit-docs/pull/17
=> feat: set up sendgrid mail integration

.eslintrc.cjs, src/features/feedback/api/useFilterFeedback.ts, src/features/feedback/components/FeedbackActionsModal/DeleteFeedbackContent.tsx, src/features/feedback/components/FeedbackActionsModal/EditFeedbackContent.tsx, src/features/profile/api/useUser.ts, src/features/sign-in/components/SgidCallback.tsx, src/features/sign-in/components/SgidLoginButton.tsx, src/features/sign-in/components/VerificationInput.tsx, src/pages/feedback/[id].tsx, src/pages/feedback/new.tsx, src/pages/sign-in/index.tsx
All promises should be awaited
=> chore: add no floating promises rule

package-lock.json, package.json
This PR bumps the relevant aws packages so they remain in sync. Also contains security fixes flagged by dependabot
=> build(deps): bump @aws-sdk packages

next.config.mjs
=> fix: typo in CSP header

src/components/ErrorBoundary/UnexpectedErrorCard.tsx
This PR updates the error message to be more consistent in tone with the rest of the application
=> feat: update error message in unexpected error card

.storybook/main.ts, package-lock.json, package.json
Adds accessibility checks for storybook.
=> chore: add accessibility plugin for storybook

.eslintrc.cjs, .gitignore, package-lock.json, package.json, tests/load/README.md, tests/load/create-post.test.ts, tests/load/create-post.ts, tests/load/webpack.config.js, vitest.config.ts
=> test: create load test example

.devcontainer/devcontainer.json
should be at least 32 characters to follow env validation
=> feat: update example session secret for devcontainer

package-lock.json
=> build(deps-dev): bump store2 to 2.14.3 to pick up MIT license

src/server/modules/auth/email/__tests__/email.router.test.ts, src/server/modules/post/__tests__/post.router.test.ts, src/server/trpc.ts
=> feat: use new createCallerFactory function for tests

package-lock.json, package.json, src/schemas/url.ts
Validate callback URLs with URL validator from [starter-kitty](https://github.com/opengovsg/starter-kitty/tree/develop/packages/validators). This fixes potential open redirects and XSS issues caused by Next.js `router.push()` behaviour.
=> fix: possible open redirect, xss

.github/workflows/ci.yml
=> refactor(ci): use new arg keys for datadog test visibility action

.github/workflows/ci.yml
=> fix(ci): fix node options generation for unit tests

package-lock.json, package.json
This pull request includes a small update to the `package.json` file. The change involves updating the `@opengovsg/sgid-client` dependency to a newer version.
Dependency update:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L54-R54): Updated `@opengovsg/sgid-client` from version `^2.2.0` to `^2.3.0`.
=> feat: update @opengovsg/sgid-client to v2.3.0
